### ISSUE TITLE
Not Working anymore

### ISSUE THREAD

**Issue by afzafri** [afzafri/KTMB-Train-Ticket-Checker#1]
KTMB website has changed their UI, and also remove the old JSON API. 

**Solution:** fetch new API link. but as for the train list result, there are no JSON API for it.
Normally we can just scrape the webpage, but in this case, the website are using AngularJS, so we can't scrape it directly. Might need to use headless browser.

New API links:
~~**Origin list:** https://intranet.ktmb.com.my/e-ticket/api/ondlist
**Destination list:** https://intranet.ktmb.com.my/e-ticket/api/ondlist?origincode=11600
**Result:** https://intranet.ktmb.com.my/ktmb_ui/ticket/select?origin=11600&destination=45800&odate=21/11/2017&rdate=undefined&pcode=undefined&adult=1&child=0&isreturn=0
**Ticket type:** https://intranet.ktmb.com.my/e-ticket/api/TICKETTYPELIST?DateJourney=21/11/2017
**List coach availability:** https://intranet.ktmb.com.my/e-ticket/api/LABELLIST?OriginCode=11600&DestinationCode=45800&DateJourney=21/11/2017&TrainNumber=9520&CoachCode=ETS2
**Slot detail:** https://intranet.ktmb.com.my/e-ticket/api/SLOTLIST?OriginCode=11600&DestinationCode=45800&DateJourney=21/11/2017&TrainNumber=9520&CoachCode=ETS2&Label=A~~

**Comment by tcmean** [comment]
Possible to do it through their mobile web? 
For example: https://eticket.ktmb.com.my/ktmb_mw/ticket/select?origin=37500&destination=37600&odate=07/10/2018&oth=NI&rdate=undefined&rth=undefined&pcode=undefined&adult=2&child=0&isreturn=0

**Comment by afzafri** [comment]
Hey thank you so much for this. This is great! I have take a look into the website, and looks like there is an open API that can be used! Looks like I can fix the project. Thank You!

**Comment by afzafri** [comment]
- This project is finally fixed thanks to [tcmean](https://github.com/tcmean) for the head up about the new KTMB ticket website.
- I was able to find new API from the new website and used it for this project.
- This project is now fully client side application as it does not need to use PHP anymore, as the new API is CORS enabled which allow it to be access cross domain.

**Comment by afzafri** [comment]
KTMB updated their API endpoint again, this time they enforce the CORS and return 403 forbidden if try to access the API endpoint directly. Looking for helps to fix this.

**Comment by afzafri** [comment]
Updated with new API. Now working again.
